DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM all_tables WHERE upper(table_name) = 'ITEM';
  IF c > 0 THEN
    EXECUTE immediate 'drop table item';
  END IF;
  
  SELECT COUNT(*) INTO c FROM all_tables WHERE upper(table_name) = 'INVOICE';
  IF c > 0 THEN
    EXECUTE immediate 'drop table INVOICE';
  END IF;
  
  SELECT COUNT(*) INTO c FROM all_tables WHERE upper(table_name) = 'PRODUCT';
  IF c > 0 THEN
    EXECUTE immediate 'drop table PRODUCT';
  END IF;
  
  SELECT COUNT(*) INTO c FROM all_tables WHERE upper(table_name) = 'CUSTOMER';
  IF c > 0 THEN
    EXECUTE immediate 'drop table CUSTOMER';
  END IF;
  
  SELECT COUNT(*) INTO c FROM all_tables WHERE upper(table_name) = 'STATES';
  IF c > 0 THEN
    EXECUTE immediate 'drop table STATES';
  END IF;
END;|

CREATE TABLE CUSTOMER(CUSTOMER_ID NUMBER(11) NOT NULL PRIMARY KEY,FIRST_NAME VARCHAR2(30) NOT NULL, LAST_NAME VARCHAR2(30) NOT NULL,STREET VARCHAR2(30) NOT NULL,CITY VARCHAR2(30) NOT NULL, PHONE VARCHAR2(30) NULL)|
CREATE TABLE PRODUCT(PRODUCT_ID NUMBER(11) NOT NULL PRIMARY KEY, NAME VARCHAR2(30) NOT NULL, PRICE NUMBER NOT NULL, COMMENTS VARCHAR2(255))|
CREATE TABLE INVOICE(INVOICE_ID NUMBER(11) NOT NULL PRIMARY KEY,CUSTOMER_ID NUMBER(11) NOT NULL,TOTAL NUMBER NOT NULL,CONSTRAINT SYS_FK_1 FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID))|
CREATE TABLE ITEM(INVOICE_ID NUMBER(11) NOT NULL,ITEM NUMBER(11) NOT NULL,PRODUCT_ID NUMBER(11) NOT NULL, QUANTITY NUMBER(11) NOT NULL,COST NUMBER NOT NULL,CONSTRAINT SYS_PK_ITEM PRIMARY KEY(INVOICE_ID,ITEM),CONSTRAINT SYS_FK_4 FOREIGN KEY(INVOICE_ID) REFERENCES INVOICE(INVOICE_ID),CONSTRAINT SYS_FK_5 FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID))|
CREATE TABLE STATES (STATE_ID VARCHAR2(3) NOT NULL PRIMARY KEY,STATE_NAME VARCHAR2(24) NOT NULL,STATE_CAPITOL VARCHAR2(24) NOT NULL,COUNTRY VARCHAR2(3) NOT NULL,REGION VARCHAR2(7) NOT NULL)|
