package org.julp.gui.generator;

import info.clearthought.layout.TableLayout;
import javax.swing.border.*;
import java.awt.*;

public class GenerationOptionsPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 150785879169301965L;
    
    /** Creates new form GenerationOptionsPanel */
    public GenerationOptionsPanel() {
        // b - border
        // f - FILL
        // p - PREFERRED
        // vs - vertical space between labels and text fields
        // vg - vertical gap between form elements
        // hg - horizontal gap between form elements
        
        double b = 5;
        double f = TableLayout.FILL;
        double p = TableLayout.PREFERRED;
        double vs = 5;
        double vg = 10;
        double hg = 5;        
        
        double size[][] = {
            {b, p, hg, p, hg, b},            
            {b, p, vs, p, vs, p, vs, p, vs, p, b}
        };        
        this.setLayout(new TableLayout(size));
        this.setBorder(new TitledBorder(new EtchedBorder(Color.WHITE, Color.GRAY), "Generate")); 
        spacerLabel.setMaximumSize(new java.awt.Dimension(120, 30));
        spacerLabel.setMinimumSize(new java.awt.Dimension(90, 16));
        spacerLabel.setPreferredSize(new java.awt.Dimension(100, 20));
        this.add(spacerLabel, "1, 1");   
        
        generateJavaBeanCheckBox.setMaximumSize(new java.awt.Dimension(400, 30));
        generateJavaBeanCheckBox.setMinimumSize(new java.awt.Dimension(100, 16));
        generateJavaBeanCheckBox.setPreferredSize(new java.awt.Dimension(300, 20));
        generateJavaBeanCheckBox.setFont(new java.awt.Font("Default", 0, 12));
        
        generateJavaBeanCheckBox.setEnabled(false);
        generateJavaBeanCheckBox.setSelected(true);
        
        generateMappingsFormCheckBox.setFont(new java.awt.Font("Default", 0, 12));
        generateMappingsFormCheckBox.setEnabled(false);
        generateMappingsFormCheckBox.setSelected(true);
        
        generateFactoryCheckBox.setFont(new java.awt.Font("Default", 0, 12));
        generateFactoryCheckBox.setEnabled(false);
        generateFactoryCheckBox.setSelected(true);        
        
        generateSwingFormCheckBox.setFont(new java.awt.Font("Default", 0, 12));
        generateSwingFormCheckBox.setSelected(true);
        generateHtmlFormCheckBox.setSelected(true);
        generateHtmlFormCheckBox.setFont(new java.awt.Font("Default", 0, 12));
        this.add(generateJavaBeanCheckBox, "3, 1");
        this.add(generateMappingsFormCheckBox, "3, 3");
        this.add(generateFactoryCheckBox, "3, 5");
        this.add(generateSwingFormCheckBox, "3, 7");
        this.add(generateHtmlFormCheckBox, "3, 9");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents

    public javax.swing.JCheckBox getGenerateSwingFormCheckBox() {
        return generateSwingFormCheckBox;
    }
    
    public javax.swing.JCheckBox getGenerateHtmlFormCheckBox() {
        return generateHtmlFormCheckBox;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    protected javax.swing.JLabel spacerLabel = new javax.swing.JLabel(" ");
    protected javax.swing.JCheckBox generateJavaBeanCheckBox = new javax.swing.JCheckBox("JavaBean");
    protected javax.swing.JCheckBox generateMappingsFormCheckBox = new javax.swing.JCheckBox("Mappings");
    protected javax.swing.JCheckBox generateFactoryCheckBox = new javax.swing.JCheckBox("Factory");    
    protected javax.swing.JCheckBox generateSwingFormCheckBox = new javax.swing.JCheckBox("Swing Form");
    protected javax.swing.JCheckBox generateHtmlFormCheckBox = new javax.swing.JCheckBox("HTML Form");
    protected javax.swing.JButton okButton = new javax.swing.JButton("OK");
}
