findAllCustomers=SELECT * FROM CUSTOMER
findAllCustomersWithPhone=SELECT * FROM CUSTOMER WHERE PHONE IS NOT NULL
findTheBiggestSpender=SELECT * FROM CUSTOMER WHERE CUSTOMER_ID = (SELECT CUSTOMER_ID FROM INVOICE WHERE INVOICE.TOTAL = (SELECT MAX(TOTAL) FROM INVOICE))
inClause1=SELECT * FROM CUSTOMER WHERE LAST_NAME <> ? AND CUSTOMER_ID IN (:#)
inClause2=SELECT * FROM CUSTOMER WHERE :#