package simpleorm.new_db;

/**Business rules class for table XX_DATA_TYPES.<br>
* Will not be regenerated by SimpleORMGenerator, add any business rules to this class
**/

public class XxDataTypes extends XxDataTypes_gen implements java.io.Serializable {

}
