package simpleorm.new_db;

/**Business rules class for table XX_DEPARTMENT.<br>
* Will not be regenerated by SimpleORMGenerator, add any business rules to this class
**/

public class XxDepartment extends XxDepartment_gen implements java.io.Serializable {

}
