package simpleorm.new_db;

/**Business rules class for table XX_EMPLOYEE.<br>
* Will not be regenerated by SimpleORMGenerator, add any business rules to this class
**/

public class XxEmployee extends XxEmployee_gen implements java.io.Serializable {

}
