package simpleorm.new_db;

/**Business rules class for table XX_INVOICE.<br>
* Will not be regenerated by SimpleORMGenerator, add any business rules to this class
**/

public class XxInvoice extends XxInvoice_gen implements java.io.Serializable {

}
