package simpleorm.new_db;
import simpleorm.dataset.*;
import simpleorm.utils.*;
import simpleorm.sessionjdbc.SSessionJdbc;
import java.math.BigDecimal;
import java.util.Date;

/**	Base class of table XX_INVOICE.<br>
*Do not edit as will be regenerated by running SimpleORMGenerator
*Generated on Wed Dec 10 14:47:40 EST 2008
***/
abstract class XxInvoice_gen extends SRecordInstance implements java.io.Serializable {

   public static final SRecordMeta <XxInvoice> meta = new SRecordMeta<XxInvoice>(XxInvoice.class, "XX_INVOICE");

//Columns in table
   public static final SFieldLong fldInvoiceNr =
      new SFieldLong(meta, "INVOICE_NR",
         new SFieldFlags[] { SFieldFlags.SPRIMARY_KEY, SFieldFlags.SMANDATORY });

   public static final SFieldString fldIname =
      new SFieldString(meta, "INAME", 40);

   public static final SFieldDouble fldIvalue =
      new SFieldDouble(meta, "IVALUE");

//Column getters and setters
   public long get_fldInvoiceNr(){ return getLong(fldInvoiceNr);}
   public void set_fldInvoiceNr( long value){setLong( fldInvoiceNr,value);}

   public String get_fldIname(){ return getString(fldIname);}
   public void set_fldIname( String value){setString( fldIname,value);}

   public BigDecimal get_fldIvalue(){ return getBigDecimal(fldIvalue);}
   public void set_fldIvalue( BigDecimal value){setBigDecimal( fldIvalue,value);}

//Find and create
   public static XxInvoice findOrCreate( SSessionJdbc ses ,long _fldInvoiceNr ){
      return ses.findOrCreate(meta, new Object[] {new Long( _fldInvoiceNr)});
   }
//specializes abstract method
   public SRecordMeta getMeta() {
       return meta;
   }
}
