package simpleorm.new_db;

/**Business rules class for table XX_LECTURER.<br>
* Will not be regenerated by SimpleORMGenerator, add any business rules to this class
**/

public class XxLecturer extends XxLecturer_gen implements java.io.Serializable {

}
