package simpleorm.new_db;
import simpleorm.dataset.*;
import simpleorm.utils.*;
import simpleorm.sessionjdbc.SSessionJdbc;
import java.math.BigDecimal;
import java.util.Date;

/**	Base class of table XX_STUDENT.<br>
*Do not edit as will be regenerated by running SimpleORMGenerator
*Generated on Wed Dec 10 14:47:40 EST 2008
***/
abstract class XxStudent_gen extends SRecordInstance implements java.io.Serializable {

   public static final SRecordMeta <XxStudent> meta = new SRecordMeta<XxStudent>(XxStudent.class, "XX_STUDENT");

//Columns in table
   public static final SFieldString fldPersonId =
      new SFieldString(meta, "PERSON_ID", 20,
         new SFieldFlags[] { SFieldFlags.SPRIMARY_KEY, SFieldFlags.SMANDATORY });

   public static final SFieldString fldPname =
      new SFieldString(meta, "PNAME", 40);

   public static final SFieldString fldPhoneNr =
      new SFieldString(meta, "PHONE_NR", 20);

   public static final SFieldString fldLecturerId =
      new SFieldString(meta, "LECTURER_ID", 20);

   public static final SFieldString fldSgrade =
      new SFieldString(meta, "SGRADE", 20);

//Column getters and setters
   public String get_fldPersonId(){ return getString(fldPersonId);}
   public void set_fldPersonId( String value){setString( fldPersonId,value);}

   public String get_fldPname(){ return getString(fldPname);}
   public void set_fldPname( String value){setString( fldPname,value);}

   public String get_fldPhoneNr(){ return getString(fldPhoneNr);}
   public void set_fldPhoneNr( String value){setString( fldPhoneNr,value);}

   public String get_fldLecturerId(){ return getString(fldLecturerId);}
   public void set_fldLecturerId( String value){setString( fldLecturerId,value);}

   public String get_fldSgrade(){ return getString(fldSgrade);}
   public void set_fldSgrade( String value){setString( fldSgrade,value);}

//Foreign key getters and setters
   public XxLecturer get_refXxLecturer(SSessionJdbc ses){
     try{
/** Old code: 
        return XxLecturer.findOrCreate(get_fldLecturerId());
New code below :**/
        return ses.findOrCreate(XxLecturer.meta,new Object[]{ 
        	get_fldLecturerId(),
 });
     } catch (SException e) {
        if (e.getMessage().indexOf("Null Primary key") > 0) {
          return null;
        }
        throw e;
     }
   }
   public void set_refXxLecturer( XxLecturer value){
      set_fldLecturerId( value.get_fldPersonId());
   }

//Find and create
   public static XxStudent findOrCreate( SSessionJdbc ses ,String _fldPersonId ){
      return ses.findOrCreate(meta, new Object[] {_fldPersonId});
   }
//specializes abstract method
   public SRecordMeta getMeta() {
       return meta;
   }
}
