package simpleorm.new_db;

/**Business rules class for table XX_STUDENT.<br>
* Will not be regenerated by SimpleORMGenerator, add any business rules to this class
**/

public class XxStudent extends XxStudent_gen implements java.io.Serializable {

}
