package org.julp.gui.swing.config;

import java.awt.event.ActionListener;
import javax.swing.UIManager;

public class ConfigurationEditorFrame extends javax.swing.JFrame implements ActionListener {

    private static final long serialVersionUID = -2594690513719041353L;
    protected ConfigurationEditorPanel configurationEditorPanel;

    public ConfigurationEditorFrame() {
        initComponents();
        configurationEditorPanel = new ConfigurationEditorPanel(true);
        configurationEditorPanel.addExitListener(this);
        //configurationEditorPanel.setCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(configurationEditorPanel, java.awt.BorderLayout.CENTER);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuration");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-600)/2, (screenSize.height-400)/2, 600, 400);
    }
    // </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        int defaultFontSize = 11;
        javax.swing.plaf.FontUIResource f = new javax.swing.plaf.FontUIResource("Sans", java.awt.Font.PLAIN, defaultFontSize);
        java.util.Enumeration keys = UIManager.getDefaults().keys();
        while (keys.hasMoreElements()) {
            Object key = keys.nextElement();
            Object value = UIManager.get(key);
            if (value instanceof javax.swing.plaf.FontUIResource) {
                UIManager.put(key, f);
            }
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ConfigurationEditorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void actionPerformed(java.awt.event.ActionEvent actionEvent) {
//        System.out.println(actionEvent.getActionCommand());
//        System.out.println(actionEvent);
        if (actionEvent.getActionCommand().equals("Close")) {
            this.setVisible(false);
            this.dispose();
        }
    }

    public ConfigurationEditorPanel getConfigurationEditorPanel() {
        return configurationEditorPanel;
    }

    public void setConfigurationEditorPanel(ConfigurationEditorPanel configurationEditorPanel) {
        this.configurationEditorPanel = configurationEditorPanel;
    }
}
