package org.julp.gui.swing.frame;

public class CommonTreeTabMaintenanceInternalFrame extends CommonMaintenanceInternalFrame {
    private static final long serialVersionUID = 6617282373739035624L;

    /** Creates new form CommonTreeTabMaintenanceInternalFrame */
    public CommonTreeTabMaintenanceInternalFrame() {
        initComponents();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        double w = screenSize.getWidth();
        double columWidth = w / 3;
        double dividerLocation = columWidth;
        int i = (int) java.lang.Math.floor(dividerLocation);
        jSplitPane1.setDividerLocation(i);
        jSplitPane1.setLastDividerLocation(i);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jSplitPane1 = new javax.swing.JSplitPane();
        treeScrollPane = new javax.swing.JScrollPane();
        tabScrollPane = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setFont(new java.awt.Font("Default", 0, 12));
        jSplitPane1.setLastDividerLocation(100);
        jSplitPane1.setAutoscrolls(true);
        jSplitPane1.setOneTouchExpandable(true);
        jSplitPane1.setLeftComponent(treeScrollPane);

        tabScrollPane.setViewportView(jTabbedPane1);

        jSplitPane1.setRightComponent(tabScrollPane);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JSplitPane jSplitPane1;
    protected javax.swing.JTabbedPane jTabbedPane1;
    protected javax.swing.JScrollPane tabScrollPane;
    protected javax.swing.JScrollPane treeScrollPane;
    // End of variables declaration//GEN-END:variables
}
